-- Phase 2: AMI → call_logs (reference DDL; carrier-api applies the same via `db.ts` migrations)
-- Database: iprn_system
--
-- Manual run (if not using carrier-api startup migration):
--
-- ALTER TABLE `call_logs` ADD COLUMN `uniqueid` VARCHAR(50) NULL;
-- ALTER TABLE `call_logs` ADD COLUMN `linkedid` VARCHAR(64) NULL;
-- ALTER TABLE `call_logs` ADD COLUMN `vendor_id` INT UNSIGNED NULL;
-- ALTER TABLE `call_logs` ADD COLUMN `start_time` DATETIME NULL;
-- ALTER TABLE `call_logs` ADD COLUMN `prefix` VARCHAR(32) NULL;
-- CREATE UNIQUE INDEX `uk_call_logs_uniqueid` ON `call_logs` (`uniqueid`);
-- CREATE INDEX `idx_call_logs_linkedid` ON `call_logs` (`linkedid`);
